# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apic < Formula
  desc "The api catalog cli"
  homepage "https://github.com/1-platform/api-catalog"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/akhilmhdh/api-catalog/releases/download/v0.1.0/api-catalog_Darwin_arm64.tar.gz"
      sha256 "1690c365e63516e4a5d5020ba9581b7fdcb0fbbc1e32bbd4001493ae0fbf5719"

      def install
        bin.install "apic"
        bash_completion.install "completions/apic.bash" => "apic"
        zsh_completion.install "completions/apic.zsh" => "_apic"
        fish_completion.install "completions/apic.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/akhilmhdh/api-catalog/releases/download/v0.1.0/api-catalog_Darwin_x86_64.tar.gz"
      sha256 "45bc7bbc96743d367d5bb8d06aafac81854bd43a7d2e4505fb255b9ea3988306"

      def install
        bin.install "apic"
        bash_completion.install "completions/apic.bash" => "apic"
        zsh_completion.install "completions/apic.zsh" => "_apic"
        fish_completion.install "completions/apic.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akhilmhdh/api-catalog/releases/download/v0.1.0/api-catalog_Linux_arm64.tar.gz"
      sha256 "f43bd6b95044557228d07ea73d0df692aba51dcc3a2389be387b77e74ceb6b66"

      def install
        bin.install "apic"
        bash_completion.install "completions/apic.bash" => "apic"
        zsh_completion.install "completions/apic.zsh" => "_apic"
        fish_completion.install "completions/apic.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/akhilmhdh/api-catalog/releases/download/v0.1.0/api-catalog_Linux_x86_64.tar.gz"
      sha256 "2461318928849aba1c9f542bcc266b2402676826dac6d9dc51d4b8a2b55000a0"

      def install
        bin.install "apic"
        bash_completion.install "completions/apic.bash" => "apic"
        zsh_completion.install "completions/apic.zsh" => "_apic"
        fish_completion.install "completions/apic.fish"
      end
    end
  end
end
