# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apic < Formula
  desc "The api catalog cli"
  homepage "https://github.com/1-platform/api-catalog"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/1-Platform/api-catalog/releases/download/v0.1.0/api-catalog_Darwin_arm64.tar.gz"
      sha256 "c584f2b44d034b9bc4228fff41112e932dc2499d35514e1399241fb5ea2364c0"

      def install
        bin.install "apic"
        bash_completion.install "completions/apic.bash" => "apic"
        zsh_completion.install "completions/apic.zsh" => "_apic"
        fish_completion.install "completions/apic.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/1-Platform/api-catalog/releases/download/v0.1.0/api-catalog_Darwin_x86_64.tar.gz"
      sha256 "2aaa387476ff0216d11a362680ff13ebd64671532e67d45418241e864231221a"

      def install
        bin.install "apic"
        bash_completion.install "completions/apic.bash" => "apic"
        zsh_completion.install "completions/apic.zsh" => "_apic"
        fish_completion.install "completions/apic.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/1-Platform/api-catalog/releases/download/v0.1.0/api-catalog_Linux_arm64.tar.gz"
      sha256 "f658f00798b32c5899aaca042f052f3f87a300c42ae113047ffd899992b0d25e"

      def install
        bin.install "apic"
        bash_completion.install "completions/apic.bash" => "apic"
        zsh_completion.install "completions/apic.zsh" => "_apic"
        fish_completion.install "completions/apic.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/1-Platform/api-catalog/releases/download/v0.1.0/api-catalog_Linux_x86_64.tar.gz"
      sha256 "d72162fd54f342cf7486373f4d22c7d9b5e8ea679b3686d523067564336d3fd6"

      def install
        bin.install "apic"
        bash_completion.install "completions/apic.bash" => "apic"
        zsh_completion.install "completions/apic.zsh" => "_apic"
        fish_completion.install "completions/apic.fish"
      end
    end
  end
end
