# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apic < Formula
  desc "The api catalog cli"
  homepage "https://github.com/1-platform/api-catalog"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/1-Platform/api-catalog/releases/download/v0.1.0/api-catalog_Darwin_arm64.tar.gz"
      sha256 "aa5a7244f14bda4aadc54f4f7585a8a0cddc2e81a133d025913407e3e29176f6"

      def install
        bin.install "apic"
        bash_completion.install "completions/apic.bash" => "apic"
        zsh_completion.install "completions/apic.zsh" => "_apic"
        fish_completion.install "completions/apic.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/1-Platform/api-catalog/releases/download/v0.1.0/api-catalog_Darwin_x86_64.tar.gz"
      sha256 "ed9f292795af88c059807c4842cab5ba0bf9cbde9733a14d5411a6a0449c32df"

      def install
        bin.install "apic"
        bash_completion.install "completions/apic.bash" => "apic"
        zsh_completion.install "completions/apic.zsh" => "_apic"
        fish_completion.install "completions/apic.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/1-Platform/api-catalog/releases/download/v0.1.0/api-catalog_Linux_arm64.tar.gz"
      sha256 "30fc61fd6fdd1b629113ede43c0df9b185d5d6bf08f22a4bff54d5372bfc290d"

      def install
        bin.install "apic"
        bash_completion.install "completions/apic.bash" => "apic"
        zsh_completion.install "completions/apic.zsh" => "_apic"
        fish_completion.install "completions/apic.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/1-Platform/api-catalog/releases/download/v0.1.0/api-catalog_Linux_x86_64.tar.gz"
      sha256 "3f6492628d20b24c434fcaa907d5db7ce131f5acd61527c5164203f9e2cc4d41"

      def install
        bin.install "apic"
        bash_completion.install "completions/apic.bash" => "apic"
        zsh_completion.install "completions/apic.zsh" => "_apic"
        fish_completion.install "completions/apic.fish"
      end
    end
  end
end
